### ISSUE TITLE
CentOS 7 - Controller Install

### ISSUE THREAD

**Issue by pynixadm** [olegzhr/AlertflexCtrl#1]
Hey,

First, let me say I really like the look of this project. The integrations with so many OSS projects was what brought me here.

Second,

We're looking at standing this up as an alternative to OSSIM (something with built-in/simple GrayLog Integration) and this came up in a search of the GrayLog Marketplace. We have a fairly controlled environment to set this up in, and our shop is most experienced with RedHat/CentOS. Is it possible to look into setting the Contoller up on CentOS 7?

Also, Maybe look at adding an ISO (full operating system) or a VM image, as well as potentially a Docker image and you may draw in a bunch more people.

Again, nice project!

Cheers.

**Comment by olegzhr** [comment]
Hi,

at this moment, Alertflex is migrating to microservices architecture so the release of Docker images for components of Alertflex is planned. Concerning the installation script of the stand-alone configuration of Alertflex for CentOS, it will come soon.

Thank you for the positive feedback about the project!

Best regards

**Comment by pynixadm** [comment]
Hey,

Thanks for the heads up.

I've spent the better part of today trying to set this up and I mostly have a working system up. If you're open to feedback I've got a couple points to make it easier to install this from a Sysadmin/devops perspective (IMHO):

- remove the dependancy of having the user build the system. I noticed both install scripts are dependant on maven and (while all in the script) the user needs the packages on their system to build this. This makes it difficult in closed environments. This includes the controller, probe and graylog plugin
- As you already have nginx in as part of your splash page, you may want to configure all of the pages to be available through an http reverse proxy and then serve all your pages (with protections as needed) over 80/443
- If you are still planning to use/develop the install script, consider making it more failure resistant with tests and exiting when something fails instead of continuing on no matter what. IE, test all external urls first to ensure you can get all packages, or even just the availability of them on some systems (ie a redhat system with satellite configured)
- For the probe/controller connection: I had a hell of a time setting this up - and I'm not sure what fixed it in the end, Consider making this more intuitive if possible
- In the controller web interface, the menu always seems to reset back to alerts no matter what, Maybe find a way to make this persistant (this could definately be my configuration here too)
- I'm sure you've heard this one already, but documentation. I found myself guessing and working through trial and error to get things working

All critisms asside, this seems like a great project and I look forward to trying out your new releases in the future. I'll definately be keeping an eye on this project as I can see potential here as a simpler system to setup than Wazuh (with integration) and less bulky than OSSIM.

Keep up the good work!
